name: CI

on: 
  push:
    branches: [master, feature/*]

jobs: 
  test: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
    - uses: actions/checkout@v2

    - name: Install node modules
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}
      run: npm install

    - name: Run tests
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}
      run: npm run test:ci
